/*! Oráculo — 509 frases originais, offline, sem números */
(() => {
  const $ = (s) => document.querySelector(s);
  const elText =
    $('#oracleMsg') || $('#oracleText') || $('#oracle-msg') || $('#oracle_text');
  const btnNova =
    $('#btnNova') || $('#btnNovaMensagem') || $('#oracle-new') || $('#btn-oraculo-nova');
  const btnCopiar =
    $('#btnCopiar') || $('#oracle-copy') || $('#btn-oraculo-copiar');
  const btnWhats =
    $('#btnWhats') || $('#oracle-wa') || $('#btn-oraculo-wa');
  if (!elText) return;

  const DECK = [
  "Mesmo cansado, Volta a ti e o amor organiza com presença.",
  "Mesmo cansado, Cuida do que é vivo e a esperança renasce com pés no chão.",
  "Fica perto de ti, e a alma acalma em silêncio.",
  "Hoje, Permite-te sentir — a luz expande em pequenas ações.",
  "O coração entende antes de explicar.",
  "Hoje, Volta a ti — a paciência aprende com ternura.",
  "Honra o teu ritmo. Deixa que o caminho aparece um passo de cada vez.",
  "Permite-te sentir; o corpo sabe devagar e bem.",
  "Hoje, Abranda — a tua coragem cresce com amor manso.",
  "Se doer, Faz espaço: o caminho aparece com curiosidade.",
  "Não precisas provar nada para merecer descanso.",
  "Honra o teu ritmo até que a mente sossega com ternura.",
  "Abraça a pausa até que a paciência aprende em silêncio.",
  "Volta quantas vezes for preciso.",
  "Volta a ti, e a mente sossega na direção do simples.",
  "Abraça a pausa. Deixa que o cansaço descansa com amor manso.",
  "Sem te apressares, Faz espaço; a dúvida abre espaço devagar e bem.",
  "Abraça a pausa, e o coração responde como quem confia.",
  "Sem te apressares, Aceita o silêncio; o futuro desanuvia com suavidade.",
  "Celebra o simples, e o espírito recorda sem barulho.",
  "Hoje, Entrega o controlo — a ternura conduz com pés no chão.",
  "Sê gentil contigo, e o tempo certo chega com gratidão.",
  "Sente orgulho do que já curaste.",
  "Antes de responderes, Leva a mão ao peito; a paz encontra-te com curiosidade.",
  "Tu és casa antes do mundo.",
  "Celebra o simples. Deixa que a luz expande devagar e bem.",
  "Confia no processo até que o espírito recorda um passo de cada vez.",
  "Se doer, Abranda: a paciência aprende no teu tempo.",
  "Hoje, Olha por dentro — o coração responde devagar e bem.",
  "Quando te esqueceres, Sê gentil contigo e a confiança floresce com pés no chão.",
  "Lembra-te de respirar. Deixa que a tua coragem cresce um passo de cada vez.",
  "Sem te apressares, Sente o chão; o tempo certo chega com verdade.",
  "Confia no processo. Deixa que o silêncio explica com verdade.",
  "Se doer, Sente o chão: a luz expande com verdade.",
  "Antes de responderes, Permite-te recomeçar; a paciência aprende sem te cobrares.",
  "Reconhece a verdade. Deixa que a dúvida abre espaço com pés no chão.",
  "Mesmo cansado, Diz sim ao que é e a presença cura com suavidade.",
  "Se doer, Oferece-te descanso: a confiança floresce com presença.",
  "A ternura também é coragem.",
  "Quando te esqueceres, Abraça a pausa e a esperança renasce como quem regressa a casa.",
  "Quando te esqueceres, Leva a mão ao peito e a luz expande como quem confia.",
  "Sem te apressares, Fica no essencial; a luz expande sem te cobrares.",
  "Se doer, Leva a mão ao peito: a dúvida abre espaço com amor manso.",
  "Leva a mão ao peito. Deixa que a paz encontra-te com gratidão.",
  "Mantém-te humilde. Deixa que a mente sossega com verdade.",
  "Mesmo cansado, Sorri por dentro e o cansaço descansa com suavidade.",
  "Sem te apressares, Confia no processo; a presença cura um passo de cada vez.",
  "Se doer, Diz sim ao que é: o silêncio explica com curiosidade.",
  "Se doer, Olha por dentro: a luz expande devagar e bem.",
  "Sem te apressares, Agradece o agora; o silêncio explica um passo de cada vez.",
  "Celebra o simples. Deixa que a paz encontra-te com curiosidade.",
  "A tua voz interna é nítida quando confias.",
  "Antes de responderes, Abraça a pausa; a tua coragem cresce com verdade.",
  "Entrega o controlo. Deixa que a luz expande na direção do simples.",
  "Sem te apressares, Lembra-te de respirar; o coração responde com verdade.",
  "Antes de responderes, Permite-te recomeçar; a clareza chega um passo de cada vez.",
  "Mantém-te humilde. Deixa que o tempo certo chega como quem regressa a casa.",
  "Quando te esqueceres, Escuta o corpo e a tua coragem cresce no teu tempo.",
  "Mesmo no escuro, continuas inteiro.",
  "Leva a mão ao peito. Deixa que o caminho aparece no teu tempo.",
  "Antes de responderes, Oferece-te descanso; a vergonha solta-se com presença.",
  "Faz espaço, e o silêncio explica a partir do peito.",
  "Mesmo cansado, Honra o teu ritmo e a alma acalma na direção do simples.",
  "Celebra o simples, e a intuição fala devagar e bem.",
  "Cuida do que é vivo; a confiança floresce como quem regressa a casa.",
  "Sorri por dentro até que o espírito recorda como quem regressa a casa.",
  "Sente o chão, e o espírito recorda com gratidão.",
  "Fica perto de ti. Deixa que a ternura conduz com gratidão.",
  "Sem te apressares, Celebra o simples; a clareza chega sem barulho.",
  "Sorri por dentro, e o silêncio explica com suavidade.",
  "Sê presença. Deixa que o futuro desanuvia com curiosidade.",
  "Se doer, Diz sim ao que é: o tempo certo chega devagar e bem.",
  "Confia no processo. Deixa que a presença cura de olhos abertos.",
  "Há bênçãos discretas a acontecer.",
  "Antes de responderes, Sê gentil contigo; a intuição fala devagar e bem.",
  "Quando te esqueceres, Abraça a pausa e o tempo certo chega com verdade.",
  "Mesmo cansado, Sê presença e a dúvida abre espaço na direção do simples.",
  "Sem te apressares, Aceita o silêncio; o caminho aparece um passo de cada vez.",
  "Fica perto de ti, e a dúvida abre espaço com curiosidade.",
  "O amor reorganiza o caos.",
  "Hoje, Pousa os ombros — o corpo sabe a partir do peito.",
  "Se doer, Abranda: o espírito recorda de olhos abertos.",
  "A presença afina o mundo.",
  "Hoje, Lembra-te de respirar — a dúvida abre espaço com ternura.",
  "Lembra-te de respirar até que o medo diminui devagar e bem.",
  "Antes de responderes, Lembra-te de respirar; a paciência aprende com gratidão.",
  "Se doer, Permite-te recomeçar: a confiança floresce na direção do simples.",
  "Mantém-te humilde até que o silêncio explica como quem confia.",
  "O teu ritmo não é atraso, é sabedoria.",
  "Sem te apressares, Abraça a pausa; o caminho aparece sem barulho.",
  "Sem te apressares, Permite-te recomeçar; a esperança renasce sem pressa.",
  "Abranda; a mente sossega com verdade.",
  "Hoje, Volta a ti — a luz expande na direção do simples.",
  "Sem te apressares, Abranda; a presença cura com gratidão.",
  "Volta a ti; o silêncio explica no teu tempo.",
  "O teu ‘não’ também é sagrado.",
  "Mesmo cansado, Sente o chão e o medo diminui com presença.",
  "Sem te apressares, Celebra o simples; o futuro desanuvia em pequenas ações.",
  "Há mar entre um pensamento e outro.",
  "Celebra o simples, e o amor organiza como quem confia.",
  "Volta a ti; o futuro desanuvia com respeito por ti.",
  "Mantém-te humilde; a paciência aprende com amor manso.",
  "Aquece o coração até que a mente sossega com ternura.",
  "Se doer, Abranda: o coração responde com presença.",
  "Hoje, Fica perto de ti — a luz expande com gratidão.",
  "Hoje, Reconhece a verdade — o corpo sabe sem barulho.",
  "Olha por dentro até que a luz expande com presença.",
  "Permite-te sentir, e a vergonha solta-se com verdade.",
  "Fica perto de ti até que a tua coragem cresce sem barulho.",
  "Hoje, Aquece o coração — a vergonha solta-se na direção do simples.",
  "Sem te apressares, Sorri por dentro; o amor organiza de olhos abertos.",
  "Sem te apressares, Pousa os ombros; a paciência aprende com curiosidade.",
  "Sem te apressares, Sê gentil contigo; a mente sossega com amor manso.",
  "Se doer, Aceita o silêncio: o caminho aparece na direção do simples.",
  "Oferece-te descanso. Deixa que a esperança renasce sem pressa.",
  "Volta a ti até que a paciência aprende com ternura.",
  "Antes de responderes, Volta a ti; a esperança renasce com pés no chão.",
  "Hoje, Fica no essencial — o corpo sabe sem te cobrares.",
  "Antes de responderes, Lembra-te de respirar; o caminho aparece um passo de cada vez.",
  "Leva a mão ao peito. Deixa que o cansaço descansa com suavidade.",
  "Sê fiel ao que te mantém vivo.",
  "Respira fundo até que o tempo certo chega com curiosidade.",
  "Antes de responderes, Sorri por dentro; a confiança floresce com respeito por ti.",
  "Abranda, e a mente sossega com suavidade.",
  "Sem te apressares, Lembra-te de respirar; a paz encontra-te sem barulho.",
  "Hoje, Oferece-te descanso — o medo diminui sem pressa.",
  "Quando te esqueceres, Escuta o corpo e a confiança floresce a partir do peito.",
  "Toma o teu lugar com quietude.",
  "Lembra-te de respirar, e a presença cura sem te cobrares.",
  "Sem te apressares, Olha por dentro; a luz expande um passo de cada vez.",
  "Fica perto de ti até que o caminho aparece de olhos abertos.",
  "Hoje, Celebra o simples — a ternura conduz sem te cobrares.",
  "Respira fundo; a vergonha solta-se com curiosidade.",
  "Sem te apressares, Sorri por dentro; o silêncio explica com amor manso.",
  "Mesmo cansado, Lembra-te de respirar e a paz encontra-te em pequenas ações.",
  "Mesmo cansado, Abranda e o tempo certo chega com gratidão.",
  "Pousa os ombros; a paciência aprende com suavidade.",
  "Confia no processo; a tua coragem cresce em pequenas ações.",
  "Abraça a pausa, e a esperança renasce no teu tempo.",
  "Respira fundo. Deixa que o silêncio explica como quem regressa a casa.",
  "Hoje, Diz sim ao que é — o medo diminui com pés no chão.",
  "Oferece-te descanso, e a paciência aprende como quem confia.",
  "Antes de responderes, Honra o teu ritmo; o tempo certo chega com ternura.",
  "Abranda; a presença cura com respeito por ti.",
  "Sem te apressares, Volta a ti; o coração responde em pequenas ações.",
  "Confia no processo; o amor organiza sem barulho.",
  "Hoje, Aceita o silêncio — a presença cura a partir do peito.",
  "Hoje, Fica no essencial — a esperança renasce com pés no chão.",
  "Agradece o agora até que a luz expande sem barulho.",
  "Abranda, e a vergonha solta-se a partir do peito.",
  "Sem te apressares, Agradece o agora; o corpo sabe com suavidade.",
  "Pousa os ombros. Deixa que o espírito recorda na direção do simples.",
  "Mesmo cansado, Leva a mão ao peito e o espírito recorda com verdade.",
  "Mesmo cansado, Celebra o simples e a intuição fala sem pressa.",
  "Se doer, Leva a mão ao peito: a mente sossega devagar e bem.",
  "Quando te esqueceres, Aceita o silêncio e o espírito recorda na direção do simples.",
  "Antes de responderes, Escuta o corpo; a clareza chega devagar e bem.",
  "Mantém-te humilde até que a esperança renasce em pequenas ações.",
  "Mesmo cansado, Agradece o agora e a esperança renasce devagar e bem.",
  "Aquece o coração até que a paz encontra-te a partir do peito.",
  "Lembra-te de respirar. Deixa que a esperança renasce em silêncio.",
  "Sente o chão, e a confiança floresce em pequenas ações.",
  "Quando te esqueceres, Sê gentil contigo e a ternura conduz com gratidão.",
  "Hoje, Fica no essencial — o cansaço descansa como quem regressa a casa.",
  "Se doer, Sê gentil contigo: a paciência aprende como quem regressa a casa.",
  "Aquece o coração; o medo diminui com pés no chão.",
  "Mesmo cansado, Celebra o simples e a paciência aprende com pés no chão.",
  "Se doer, Aquece o coração: a intuição fala com ternura.",
  "Sê presença; o amor organiza com presença.",
  "Sem te apressares, Oferece-te descanso; a presença cura com gratidão.",
  "Antes de responderes, Sente o chão; a alma acalma a partir do peito.",
  "Quando te esqueceres, Confia no processo e o coração responde com verdade.",
  "Pousa os ombros; a presença cura em pequenas ações.",
  "Quando te esqueceres, Respira fundo e a presença cura em pequenas ações.",
  "Se doer, Honra o teu ritmo: a mente sossega com gratidão.",
  "Diz sim ao que é, e a presença cura na direção do simples.",
  "Fica no essencial. Deixa que o cansaço descansa de olhos abertos.",
  "Hoje, Pousa os ombros — a presença cura com verdade.",
  "Sem te apressares, Fica no essencial; a alma acalma sem barulho.",
  "Aceitar não te diminui, liberta-te.",
  "Antes de responderes, Abraça a pausa; o espírito recorda com pés no chão.",
  "Se doer, Sê gentil contigo: a tua coragem cresce com ternura.",
  "A luz não exige; oferece.",
  "Abraça a pausa até que a mente sossega com ternura.",
  "Permitir é diferente de desistir.",
  "Honra o teu ritmo. Deixa que o espírito recorda em silêncio.",
  "Mesmo cansado, Pousa os ombros e o caminho aparece com presença.",
  "Mesmo cansado, Abraça a pausa e a ternura conduz com respeito por ti.",
  "Pousa os ombros até que a mente sossega com ternura.",
  "Se doer, Sorri por dentro: o silêncio explica na direção do simples.",
  "Antes de responderes, Aceita o silêncio; o corpo sabe na direção do simples.",
  "Antes de responderes, Abraça a pausa; a vergonha solta-se com verdade.",
  "Estás a aprender a pertencer a ti.",
  "Hoje, Sê presença — o futuro desanuvia um passo de cada vez.",
  "Hoje, Leva a mão ao peito — a luz expande na direção do simples.",
  "Sê presença até que a paz encontra-te sem te cobrares.",
  "Celebra o simples. Deixa que o caminho aparece sem te cobrares.",
  "Hoje, Confia no processo — a presença cura em pequenas ações.",
  "Antes de responderes, Sê presença; o medo diminui em silêncio.",
  "Hoje, Reconhece a verdade — o cansaço descansa sem pressa.",
  "Entrega o controlo. Deixa que a esperança renasce em silêncio.",
  "Quando soltas, a vida encontra-te.",
  "Leva a mão ao peito; a vergonha solta-se como quem regressa a casa.",
  "Se doer, Sorri por dentro: o caminho aparece no teu tempo.",
  "Quando te esqueceres, Fica no essencial e a confiança floresce com gratidão.",
  "Antes de responderes, Abraça a pausa; a mente sossega a partir do peito.",
  "Quando te esqueceres, Sê presença e a intuição fala com presença.",
  "Se doer, Abraça a pausa: o coração responde como quem regressa a casa.",
  "Permite-te sentir até que o medo diminui com curiosidade.",
  "Hoje, Permite-te sentir — o coração responde de olhos abertos.",
  "Quando te esqueceres, Celebra o simples e a luz expande em pequenas ações.",
  "A paz não é meta; é caminho.",
  "Sem te apressares, Sê presença; o silêncio explica sem barulho.",
  "Pousa os ombros; o coração responde com suavidade.",
  "Olha por dentro. Deixa que o espírito recorda como quem regressa a casa.",
  "Permite-te recomeçar, e a paciência aprende com respeito por ti.",
  "Sê gentil contigo. Deixa que o cansaço descansa como quem confia.",
  "Se doer, Respira fundo: o amor organiza com verdade.",
  "Deixar ir abre espaço para chegar.",
  "Mantém-te humilde; o tempo certo chega sem barulho.",
  "Sem te apressares, Pousa os ombros; a confiança floresce com gratidão.",
  "Mesmo cansado, Aquece o coração e o caminho aparece com ternura.",
  "Fica no essencial até que a luz expande sem te cobrares.",
  "Sê presença. Deixa que a intuição fala com ternura.",
  "Antes de responderes, Volta a ti; a intuição fala de olhos abertos.",
  "Oferece-te descanso até que a presença cura com verdade.",
  "Antes de responderes, Abraça a pausa; a ternura conduz um passo de cada vez.",
  "Mesmo cansado, Confia no processo e o coração responde com pés no chão.",
  "Mesmo cansado, Abranda e a dúvida abre espaço de olhos abertos.",
  "Mesmo cansado, Volta a ti e o coração responde sem barulho.",
  "Se doer, Sê presença: o espírito recorda com amor manso.",
  "Antes de responderes, Faz espaço; a dúvida abre espaço com presença.",
  "Fica perto de ti. Deixa que a ternura conduz com respeito por ti.",
  "Oferece-te descanso, e o medo diminui na direção do simples.",
  "Quando te esqueceres, Fica no essencial e a tua coragem cresce como quem confia.",
  "Hoje, Abraça a pausa — a tua coragem cresce em pequenas ações.",
  "Fica perto de ti. Deixa que o amor organiza sem barulho.",
  "Abraça a pausa; o caminho aparece com pés no chão.",
  "Sem te apressares, Sorri por dentro; o cansaço descansa um passo de cada vez.",
  "Antes de responderes, Lembra-te de respirar; a mente sossega devagar e bem.",
  "Volta a ti, e a dúvida abre espaço na direção do simples.",
  "Quando te esqueceres, Aceita o silêncio e a confiança floresce sem pressa.",
  "Sem te apressares, Permite-te recomeçar; o futuro desanuvia com respeito por ti.",
  "Mesmo cansado, Faz espaço e o espírito recorda com amor manso.",
  "Sem te apressares, Sê presença; a esperança renasce a partir do peito.",
  "Antes de responderes, Mantém-te humilde; a ternura conduz com respeito por ti.",
  "Reconhece a verdade, e o medo diminui com amor manso.",
  "Quando te esqueceres, Mantém-te humilde e a luz expande com ternura.",
  "O essencial não grita.",
  "Antes de responderes, Aquece o coração; a confiança floresce em pequenas ações.",
  "Mantém-te humilde; a ternura conduz com amor manso.",
  "Leva a mão ao peito. Deixa que a paz encontra-te com respeito por ti.",
  "Quando te esqueceres, Abranda e o espírito recorda com ternura.",
  "Se doer, Permite-te sentir: o medo diminui sem pressa.",
  "Volta a ti; a dúvida abre espaço na direção do simples.",
  "Mesmo cansado, Honra o teu ritmo e a clareza chega em silêncio.",
  "Diz sim ao que é, e a presença cura a partir do peito.",
  "Sem te apressares, Volta a ti; o espírito recorda de olhos abertos.",
  "Sem te apressares, Lembra-te de respirar; o coração responde a partir do peito.",
  "O azul lembra-te: estás a salvo.",
  "Mantém-te humilde até que o medo diminui com curiosidade.",
  "Sem te apressares, Celebra o simples; a esperança renasce devagar e bem.",
  "Aquece o coração; a paciência aprende devagar e bem.",
  "Sê presença. Deixa que a esperança renasce com gratidão.",
  "Hoje, Aquece o coração — a confiança floresce a partir do peito.",
  "Sorri por dentro, e a alma acalma com gratidão.",
  "Respira fundo, e a dúvida abre espaço um passo de cada vez.",
  "Quando te esqueceres, Sê gentil contigo e o cansaço descansa a partir do peito.",
  "A pausa é parte da música.",
  "Permite-te recomeçar. Deixa que o caminho aparece um passo de cada vez.",
  "Mesmo cansado, Oferece-te descanso e a alma acalma com verdade.",
  "Hoje, Pousa os ombros — o caminho aparece com pés no chão.",
  "Mesmo cansado, Diz sim ao que é e a vergonha solta-se um passo de cada vez.",
  "Se doer, Aquece o coração: a dúvida abre espaço com gratidão.",
  "Cuida do que é vivo, e a luz expande de olhos abertos.",
  "Sem te apressares, Confia no processo; a clareza chega devagar e bem.",
  "Hoje, Permite-te sentir — a tua coragem cresce no teu tempo.",
  "Sem te apressares, Reconhece a verdade; a tua coragem cresce sem te cobrares.",
  "Quando sabes pausar, sabes viver.",
  "Sem te apressares, Escuta o corpo; o cansaço descansa a partir do peito.",
  "Sem te apressares, Cuida do que é vivo; a presença cura com presença.",
  "Sê presença. Deixa que a paciência aprende na direção do simples.",
  "Quando te esqueceres, Volta a ti e a vergonha solta-se na direção do simples.",
  "Sem te apressares, Fica perto de ti; a confiança floresce com presença.",
  "Honra o teu ritmo. Deixa que o medo diminui com presença.",
  "Quando te esqueceres, Abranda e o amor organiza sem pressa.",
  "Sem te apressares, Honra o teu ritmo; a vergonha solta-se em silêncio.",
  "Antes de responderes, Diz sim ao que é; o amor organiza com ternura.",
  "Respira fundo; a intuição fala com gratidão.",
  "Hoje, Respira fundo — a paz encontra-te com verdade.",
  "Confia no processo. Deixa que a intuição fala com respeito por ti.",
  "Hoje, Pousa os ombros — o cansaço descansa como quem regressa a casa.",
  "Sem te apressares, Faz espaço; a clareza chega com pés no chão.",
  "Agradece o agora até que o cansaço descansa com respeito por ti.",
  "Mantém-te humilde; a ternura conduz com pés no chão.",
  "Se doer, Oferece-te descanso: o corpo sabe sem te cobrares.",
  "A tua sensibilidade é força, não falha.",
  "Antes de responderes, Celebra o simples; a intuição fala com pés no chão.",
  "O teu coração sabe o caminho curto.",
  "Quando te esqueceres, Aquece o coração e a esperança renasce sem barulho.",
  "Mesmo cansado, Aquece o coração e a dúvida abre espaço com respeito por ti.",
  "Sê presença; o tempo certo chega sem barulho.",
  "Fica perto de ti. Deixa que a esperança renasce de olhos abertos.",
  "Aceita o silêncio. Deixa que o corpo sabe com pés no chão.",
  "Se doer, Oferece-te descanso: o caminho aparece a partir do peito.",
  "Permite-te recomeçar. Deixa que a alma acalma em silêncio.",
  "Sorri por dentro, e a dúvida abre espaço um passo de cada vez.",
  "Entrega o controlo até que a ternura conduz com ternura.",
  "Mesmo cansado, Fica perto de ti e a luz expande como quem regressa a casa.",
  "Olha por dentro; o corpo sabe devagar e bem.",
  "Sem te apressares, Escuta o corpo; a confiança floresce com pés no chão.",
  "Sê presença. Deixa que a confiança floresce de olhos abertos.",
  "Antes de responderes, Permite-te recomeçar; a paciência aprende com amor manso.",
  "Aquece o coração, e o caminho aparece com suavidade.",
  "Quando te esqueceres, Fica perto de ti e a intuição fala com respeito por ti.",
  "Volta a ti. Deixa que a clareza chega sem barulho.",
  "Se doer, Sê gentil contigo: a clareza chega com verdade.",
  "Quando te esqueceres, Permite-te sentir e o espírito recorda com verdade.",
  "Mantém-te humilde; o medo diminui com ternura.",
  "Hoje, Aquece o coração — a alma acalma com respeito por ti.",
  "Hoje, Celebra o simples — a presença cura com amor manso.",
  "A respiração é uma porta que nunca fecha.",
  "O amor-próprio não é ego, é raiz.",
  "Antes de responderes, Fica perto de ti; a paz encontra-te como quem regressa a casa.",
  "Mesmo cansado, Oferece-te descanso e o medo diminui como quem regressa a casa.",
  "Mesmo cansado, Sê presença e o futuro desanuvia sem te cobrares.",
  "Antes de responderes, Lembra-te de respirar; a paciência aprende na direção do simples.",
  "Se doer, Sente o chão: o medo diminui em pequenas ações.",
  "Mesmo cansado, Celebra o simples e a vergonha solta-se com ternura.",
  "Mesmo cansado, Diz sim ao que é e o futuro desanuvia com gratidão.",
  "Respira fundo. Deixa que a vergonha solta-se com pés no chão.",
  "Mantém-te humilde até que o silêncio explica sem pressa.",
  "Permite-te recomeçar; a tua coragem cresce com curiosidade.",
  "Sem te apressares, Confia no processo; a paz encontra-te no teu tempo.",
  "A bondade é a tua revolução.",
  "Se doer, Cuida do que é vivo: a esperança renasce com suavidade.",
  "Hoje, Cuida do que é vivo — o espírito recorda com presença.",
  "Quando te esqueceres, Entrega o controlo e a esperança renasce com ternura.",
  "Quando te esqueceres, Lembra-te de respirar e a ternura conduz no teu tempo.",
  "A vida também te escolhe.",
  "Mesmo cansado, Agradece o agora e o silêncio explica com amor manso.",
  "Mesmo cansado, Sorri por dentro e a tua coragem cresce com gratidão.",
  "Quando te esqueceres, Volta a ti e o caminho aparece com verdade.",
  "Aceita o silêncio até que a ternura conduz de olhos abertos.",
  "Honra o teu ritmo até que a luz expande na direção do simples.",
  "Lembra-te de respirar; o cansaço descansa com ternura.",
  "Reconhece a verdade. Deixa que o silêncio explica com pés no chão.",
  "Sê presença, e a dúvida abre espaço com amor manso.",
  "Hoje, Cuida do que é vivo — a tua coragem cresce com gratidão.",
  "Hoje, Entrega o controlo — o silêncio explica no teu tempo.",
  "Permite-te recomeçar. Deixa que o tempo certo chega com presença.",
  "Se doer, Celebra o simples: o futuro desanuvia com ternura.",
  "Hoje, Respira fundo — o cansaço descansa um passo de cada vez.",
  "Permite-te sentir. Deixa que o caminho aparece um passo de cada vez.",
  "Aquece o coração até que o silêncio explica sem te cobrares.",
  "Pousa os ombros até que a alma acalma com curiosidade.",
  "Se te perderes, volta ao corpo.",
  "Confia no processo. Deixa que a mente sossega em silêncio.",
  "Antes de responderes, Confia no processo; a clareza chega com suavidade.",
  "O que é verdadeiro permanece simples.",
  "Hoje, Leva a mão ao peito — a mente sossega com verdade.",
  "Quando te esqueceres, Aceita o silêncio e o medo diminui em silêncio.",
  "Antes de responderes, Honra o teu ritmo; a clareza chega com amor manso.",
  "Confia no processo, e o silêncio explica como quem regressa a casa.",
  "Mesmo cansado, Fica perto de ti e a paz encontra-te com gratidão.",
  "O amanhã não precisa de pressa hoje.",
  "A intuição fala baixo — aproxima-te.",
  "Lembra-te de respirar; a presença cura em pequenas ações.",
  "Quando te esqueceres, Sorri por dentro e o amor organiza na direção do simples.",
  "Hoje, Reconhece a verdade — o amor organiza sem pressa.",
  "Quando te esqueceres, Celebra o simples e o corpo sabe sem barulho.",
  "Se doer, Aquece o coração: a luz expande sem te cobrares.",
  "Mantém-te humilde; a luz expande como quem regressa a casa.",
  "Se doer, Mantém-te humilde: a presença cura de olhos abertos.",
  "Celebra o simples. Deixa que o medo diminui a partir do peito.",
  "Sorri por dentro até que a vergonha solta-se com pés no chão.",
  "Hoje, Sê gentil contigo — a presença cura com curiosidade.",
  "Respira fundo. Deixa que a esperança renasce com ternura.",
  "Antes de responderes, Honra o teu ritmo; a paz encontra-te com verdade.",
  "Sê gentil contigo, e a dúvida abre espaço com verdade.",
  "Há beleza no intervalo.",
  "A coragem pode ser mansa.",
  "Quando te esqueceres, Entrega o controlo e o silêncio explica em pequenas ações.",
  "Quando te esqueceres, Celebra o simples e o amor organiza com amor manso.",
  "Quando te esqueceres, Faz espaço e o corpo sabe com suavidade.",
  "Agradece o agora. Deixa que o amor organiza como quem regressa a casa.",
  "Sê presença; o medo diminui com amor manso.",
  "Escolhe o que te devolve a ti.",
  "Mesmo cansado, Aquece o coração e o futuro desanuvia com curiosidade.",
  "Aquece o coração; o caminho aparece com ternura.",
  "Hoje, Pousa os ombros — a paciência aprende com ternura.",
  "Quando te esqueceres, Respira fundo e o cansaço descansa com curiosidade.",
  "Confia no processo; a alma acalma como quem confia.",
  "Quando te esqueceres, Sente o chão e a intuição fala em silêncio.",
  "Descansar também é trabalho de alma.",
  "O corpo não mente; escuta-o.",
  "Se doer, Honra o teu ritmo: a luz expande como quem regressa a casa.",
  "Escuta o corpo. Deixa que o futuro desanuvia sem te cobrares.",
  "O cuidado contigo é trabalho divino.",
  "Mesmo cansado, Leva a mão ao peito e o silêncio explica como quem confia.",
  "Hoje, Olha por dentro — a mente sossega com amor manso.",
  "Abranda até que a alma acalma com ternura.",
  "Se doer, Faz espaço: a ternura conduz na direção do simples.",
  "Hoje, Leva a mão ao peito — a clareza chega com pés no chão.",
  "Sem te apressares, Mantém-te humilde; a clareza chega sem te cobrares.",
  "Celebra o simples. Deixa que a dúvida abre espaço em pequenas ações.",
  "Se doer, Permite-te recomeçar: o corpo sabe com suavidade.",
  "Se doer, Pousa os ombros: o tempo certo chega com presença.",
  "Antes de responderes, Permite-te recomeçar; o espírito recorda na direção do simples.",
  "Quando te esqueceres, Aceita o silêncio e o silêncio explica a partir do peito.",
  "Quando te esqueceres, Permite-te recomeçar e a intuição fala devagar e bem.",
  "Mesmo cansado, Reconhece a verdade e o silêncio explica com curiosidade.",
  "Escuta o corpo, e a tua coragem cresce com curiosidade.",
  "Quando te esqueceres, Permite-te sentir e a tua coragem cresce como quem regressa a casa.",
  "Se doer, Honra o teu ritmo: o cansaço descansa sem barulho.",
  "A tua presença muda a sala.",
  "Abraça a pausa. Deixa que a vergonha solta-se a partir do peito.",
  "Respira fundo; a dúvida abre espaço com curiosidade.",
  "Mesmo cansado, Sê presença e a luz expande como quem regressa a casa.",
  "Cuida do que é vivo até que a esperança renasce a partir do peito.",
  "Confia no processo; a luz expande no teu tempo.",
  "Antes de responderes, Reconhece a verdade; o cansaço descansa de olhos abertos.",
  "Quando te esqueceres, Honra o teu ritmo e o medo diminui a partir do peito.",
  "Quando te esqueceres, Abranda e o cansaço descansa com ternura.",
  "Sem te apressares, Volta a ti; a confiança floresce em silêncio.",
  "Hoje, Lembra-te de respirar — o medo diminui com presença.",
  "Se doer, Sê presença: o medo diminui como quem regressa a casa.",
  "Antes de responderes, Pousa os ombros; a paz encontra-te com gratidão.",
  "Permite-te sentir até que a paciência aprende sem barulho.",
  "Antes de responderes, Sente o chão; a paciência aprende no teu tempo.",
  "Honra o teu ritmo, e a paciência aprende em silêncio.",
  "Se doer, Confia no processo: a vergonha solta-se com curiosidade.",
  "Hoje, Agradece o agora — a presença cura em silêncio.",
  "O caminho abre onde pousas atenção.",
  "Sem te apressares, Aquece o coração; o medo diminui sem barulho.",
  "Antes de responderes, Sorri por dentro; a alma acalma com presença.",
  "Quando te esqueceres, Volta a ti e a confiança floresce com verdade.",
  "Se doer, Permite-te recomeçar: a esperança renasce como quem regressa a casa.",
  "Respirar é regressar.",
  "Lembra-te de respirar; a clareza chega como quem regressa a casa.",
  "Aceita o silêncio, e a luz expande devagar e bem.",
  "Quando te esqueceres, Sê presença e a esperança renasce com verdade.",
  "Permite-te recomeçar. Deixa que a clareza chega como quem confia.",
  "Hoje, Celebra o simples — o amor organiza de olhos abertos.",
  "Olha por dentro; a tua coragem cresce em silêncio.",
  "Mesmo cansado, Volta a ti e o cansaço descansa com presença.",
  "Mesmo cansado, Mantém-te humilde e o silêncio explica sem barulho.",
  "Olha por dentro; a intuição fala com gratidão.",
  "Hoje, Agradece o agora — a intuição fala como quem regressa a casa.",
  "Há respostas que só o silêncio entrega.",
  "Hoje, Mantém-te humilde — a luz expande em silêncio.",
  "Leva a mão ao peito; o corpo sabe com amor manso.",
  "Antes de responderes, Mantém-te humilde; o cansaço descansa com verdade.",
  "Sem te apressares, Fica perto de ti; o caminho aparece como quem regressa a casa.",
  "Reconhece a verdade. Deixa que o medo diminui a partir do peito.",
  "Sê gentil contigo. Deixa que o cansaço descansa devagar e bem.",
  "Sem te apressares, Abraça a pausa; a esperança renasce devagar e bem.",
  "Respira fundo até que o medo diminui em pequenas ações.",
  "Confia no processo, e a paz encontra-te no teu tempo.",
  "Se doer, Sê gentil contigo: o tempo certo chega com respeito por ti.",
  "Entrega o controlo. Deixa que o futuro desanuvia devagar e bem.",
  "Mesmo cansado, Aceita o silêncio e a dúvida abre espaço sem pressa.",
  "Hoje, Faz espaço — o futuro desanuvia com amor manso.",
  "Sem te apressares, Pousa os ombros; a intuição fala em pequenas ações.",
  "Agradece o agora; a presença cura a partir do peito.",
  "Abraça a pausa, e o caminho aparece em pequenas ações.",
  "Leva a mão ao peito. Deixa que a dúvida abre espaço como quem confia.",
  "Sem te apressares, Faz espaço; a ternura conduz um passo de cada vez.",
  "Fica no essencial. Deixa que o corpo sabe devagar e bem.",
  "Fica no essencial, e o caminho aparece em silêncio.",
  "Hoje, Lembra-te de respirar — o futuro desanuvia com suavidade.",
  "Respira fundo; a paciência aprende como quem confia.",
  "Abraça a pausa, e o corpo sabe um passo de cada vez.",
  "Sorri por dentro. Deixa que a luz expande sem pressa.",
  "Sem te apressares, Sorri por dentro; a alma acalma na direção do simples.",
  "Quando te esqueceres, Sê gentil contigo e o coração responde a partir do peito.",
  "Se doer, Sê presença: a dúvida abre espaço em silêncio.",
  "Abranda até que o futuro desanuvia em silêncio.",
  "Antes de responderes, Volta a ti; a luz expande no teu tempo.",
  "Leva a mão ao peito; a alma acalma em pequenas ações.",
  "Diz sim ao que é. Deixa que a confiança floresce no teu tempo.",
  "Hoje, Confia no processo — o amor organiza devagar e bem.",
  "Hoje, Olha por dentro — a luz expande a partir do peito.",
  "Hoje, Fica perto de ti — o caminho aparece com suavidade.",
  "Antes de responderes, Mantém-te humilde; a presença cura com gratidão.",
  "Sente o chão; o caminho aparece com verdade.",
  "Sê gentil contigo. Deixa que a clareza chega com respeito por ti.",
  "Se doer, Sorri por dentro: a confiança floresce de olhos abertos.",
  "Mesmo cansado, Aquece o coração e a dúvida abre espaço com ternura.",
  "Mesmo cansado, Fica no essencial e o corpo sabe na direção do simples.",
  "Mesmo cansado, Lembra-te de respirar e a esperança renasce com suavidade.",
  "És suficiente agora.",
  "Antes de responderes, Aceita o silêncio; a esperança renasce de olhos abertos.",
  "Sem te apressares, Permite-te sentir; a esperança renasce com curiosidade.",
  "Sorri por dentro até que o caminho aparece sem pressa.",
  "Nem tudo pede solução; algumas coisas pedem colo.",
  "Podes começar pequeno e ainda assim começar.",
  "Mantém-te humilde, e a alma acalma de olhos abertos.",
  "Confia no processo até que o espírito recorda em pequenas ações.",
  "Mesmo cansado, Reconhece a verdade e o espírito recorda com ternura.",
  "Sente o chão, e a confiança floresce com verdade.",
  "Leva a mão ao peito, e a paciência aprende com suavidade.",
  "Aceita o silêncio até que o espírito recorda na direção do simples.",
  "Abranda, e o amor organiza com respeito por ti.",
  "Permite-te recomeçar. Deixa que o silêncio explica no teu tempo.",
  "Quando te esqueceres, Volta a ti e o amor organiza com gratidão.",
  "Hoje, Oferece-te descanso — a mente sossega como quem regressa a casa.",
  "Mantém-te humilde até que a clareza chega devagar e bem.",
  "Hoje, Aquece o coração — a esperança renasce com curiosidade."
];

  for (let i=DECK.length-1; i>0; i--) {
    const j = (Math.random()*(i+1))|0; [DECK[i], DECK[j]] = [DECK[j], DECK[i]];
  }

  let idx = 0, last = "";
  function novaFrase(){
    if (!DECK.length) return;
    if (idx >= DECK.length) { idx = 0; }
    let f = DECK[idx++];
    if (f === last && idx < DECK.length) f = DECK[idx++];
    last = f;
    elText.textContent = f;
  }
  function copiar(){
    const t = (elText.textContent||'').trim(); if (!t) return;
    if (navigator.clipboard?.writeText) navigator.clipboard.writeText(t).catch(()=>{});
    else { const ta=document.createElement('textarea'); ta.value=t; document.body.appendChild(ta); ta.select(); try{document.execCommand('copy');}catch{} ta.remove(); }
  }
  function whats(){
    const t = encodeURIComponent((elText.textContent||'').trim()); if (!t) return;
    location.href = 'https://wa.me/?text=' + t;
  }

  btnNova   && btnNova  .addEventListener('click', novaFrase);
  btnCopiar && btnCopiar.addEventListener('click', copiar);
  btnWhats  && btnWhats .addEventListener('click', whats);

  if (!elText.textContent || /Nova mensagem/i.test(elText.textContent))
    elText.textContent = "Toca em “Nova mensagem” para receber a tua mensagem.";
})();
